### model
model_name_or_path: meta-llama/Meta-Llama-3.1-8B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: ./misc/ds_z3_config.json

### dataset
dataset_dir: ./src/src/utils/
dataset: combined_3_500
template: llama3
cutoff_len: 2048
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ./saves/llama3.1-8b-instruct/full/sft/num_exploration/29-meta-llama-Meta-Llama-3.1-8B-Instruct-combined_3_500-1.0e-7
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: false

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-7
num_train_epochs: 3.0
lr_scheduler_type: linear
# warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500

